name: CI/CD Pipeline

on:
  push:
    branches: [ Backend_Configuration, Frontend_Configuration, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Backend Setup
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Run Django tests
      run: |
        cd backend/rolisticae_api/
       python manage.py test --settings=rolisticae_api.settings.dev

    # Frontend Setup
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install Node.js dependencies
      run: |
        cd frontend/rolisticae_client/
        npm install
    - name: Run React tests
      run: |
        cd frontend/rolisticae_client/
        npm test
